name: manara
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  pin_code_fields: ^8.0.1
  webview_flutter: ^4.13.0
  http: ^1.4.0
  flutter_spinkit: ^5.2.1
  audioplayers: ^6.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  colorful_safe_area: ^1.0.0
  flutter_swiper_view: ^1.1.8
  sqflite: ^2.4.2
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  provider: ^6.1.5
  fl_chart: ^1.0.0
  geolocator: ^13.0.2
  adhan: ^2.0.0+1
  permission_handler: ^12.0.1
  flutter_qiblah: ^3.1.0+1
  purchases_flutter: ^8.10.6
  onesignal_flutter: ^5.3.4
  firebase_core: ^3.15.1
  flutter_local_notifications: ^19.3.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  carousel_slider: ^5.1.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2

  youtube_player_flutter: ^9.1.1
  path_provider: ^2.1.4
  wallpaper_manager_plus: ^1.0.3
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  image_gallery_saver_plus: ^4.0.1
  arc_progress_bar_new: ^1.0.4
  app_settings: ^6.1.1
  hijri: ^3.0.0
  sliver_tools: ^0.2.12
  sensors_plus: ^6.1.1
  google_maps_flutter: ^2.12.3
  geocoding: ^4.0.0
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  toastification: ^3.0.3
  timezone: ^0.10.1
  flutter_localizations:
    sdk: flutter
  # BLoC dependencies
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  # Hive for local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # API dependencies for real mosque data
  google_places_flutter: ^2.0.6
  # Map dependencies
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  flutter_linear_datepicker: ^3.0.1
  workmanager: ^0.9.0+2
  share_plus: ^10.1.2 #Share Data
  flutter_secure_storage: ^9.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.2




flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/appico.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/images/appico.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/images/appico.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/appico.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  json_annotation: ^4.8.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/locales/
    - assets/azan/
    - assets/beads/
    - .env






  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
  #         style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
    - family: KFGQPCUthmanicScriptHAFS
      fonts:
        - asset: assets/fonts/KFGQPC Uthmanic Script HAFS.otf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
